---
# tasks file for ansible_ws_default
- name: copy blinken.sh
  copy:
    src: files/blinken.sh
    dest: /home/pi/blinken.sh
    owner: pi
    group: pi
    mode: 0770
- name: jetzt wird geblinkt
  shell: /home/pi/blinken.sh